development:
  # adapter: async
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV['REDISCLOUD_URL'] %>
  channel_prefix: weekendr_production

# redis: &redis
#   adapter: redis
#   url: redis://localhost:6379/1

# production: *redis
# development: *redis
# test: *redis
